# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: " "
email: willydjangang@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Djangang Willy Kelvin Jr - Bachelor Student @ UniUd - Software Engineering Research
url: "https://classdjwik.github.io" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog
reddit_username:  CJDWIK9KOL
github_username:  classdjwik

# Site Footer
footer:
  links:
    - label: "Reddit"
      icon: "fab fa-fw fa-reddit fa-3x"
      url: "https://www.reddit.com/user/CJDWIK9KOL/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button"
    - label: "GitHub"
      icon: "fab fa-fw fa-github fa-3x"
      url: "https://github.com/classdjwik"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin fa-3x"
      url: "www.linkedin.com/in/willy-kelvin-junior-djangang-98658124a"

author:
  name: "Vincenzo Riccio"
  #avatar: "/assets/images/Riccio.jpg"
  bio: "Bachelor Student @ UniUd" # Note: Markdown is allowed
  location: "Udine, Italy"
  links:
    #- label: "Made Mistakes"
    #  icon: ""
    #  url: "https://mademistakes.com"
     - label: "Reddit"
      icon: "fab fa-fw fa-reddit fa-3x"
      url: "https://www.reddit.com/user/CJDWIK9KOL/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button"
    - label: "GitHub"
      icon: "fab fa-fw fa-github fa-3x"
      url: "https://github.com/classdjwik"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin fa-3x"
      url: "www.linkedin.com/in/willy-kelvin-junior-djangang-98658124a"
    - label: "Google Scholar"
      icon: "ai ai-google-scholar-square"
      url: "https://scholar.google.ch/citations?user=begiotMAAAAJ"
    - label: "ResearchGate"
      icon: "fab fa-fw fa-researchgate"
      url: "https://www.researchgate.net/profile/Vincenzo-Riccio"
    #- label: "Instagram"
    #  icon: "fab fa-fw fa-instagram"
    #  url: ""

atom_feed:
  hide: true

# Build settings
# theme: "minima"
remote_theme: "mmistakes/minimal-mistakes@4.23.0"
minimal_mistakes_skin: "dark" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"
plugins:
   - jekyll-feed
   - jekyll-include-cache
   - jekyll-paginate
   - jekyll-sitemap
   - jekyll-gist
   - jemoji

# from mmist
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true


include:
  - _pages


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - path/ruby/3.0.0/gems/
  - path/ruby/3.0.0/
